<?php

if( ! defined( 'XOOPS_ROOT_PATH' ) ) exit ;

$this->messages = array(
	'err_general' => 'GTicket Error' ,
	'err_nostubs' => 'セッション内に半券が見つかりませんでした' ,
	'err_noticket' => 'チケットが投稿されていません' ,
	'err_nopair' => '有効なチケットと半券のペアが見つかりませんでした' ,
	'err_timeout' => 'チケットの有効期限切れです' ,
	'err_areaorref' => 'チケットのエリアかリファラに問題があります' ,
	'fmt_prompt4repost' => 'チケット関連のエラーが発生しました。<br /><span style="background-color:red;font-weight:bold;color:white;">%s</span><br />内容を確認の上、新しいチケットで再投稿しますか？' ,
	'btn_repost' => '再投稿する' ,
) ;


?>