<?php

if( ! defined( 'XOOPS_ROOT_PATH' ) ) exit ;

$this->messages = array(
	'err_general' => 'Erreur GTicket' ,
	'err_nostubs' => 'Aucun jeton trouv&eacute;' ,
	'err_noticket' => "Aucun ticket trouv&eacute;" ,
	'err_nopair' => "Aucune paire Ticket-jeton trouv&eacute;" ,
	'err_timeout' => 'Time out' ,
	'err_areaorref' => 'Zone ou referer invalide' ,
	'fmt_prompt4repost' => 'erreur(s) trouv&eacute;e(s)found:<br /><span style="background-color:red;font-weight:bold;color:white;">%s</span><br />Veuillez le confirmer.<br />De plus, voulez-vous poster de nouveau?' ,
	'btn_repost' => 'reposter' ,
) ;


?>