<?php

if( ! defined( 'XOOPS_ROOT_PATH' ) ) exit ;

$this->messages = array(
	'err_general' => 'GTicket Error' ,
	'err_nostubs' => 'No stubs found' ,
	'err_noticket' => 'No ticket found' ,
	'err_nopair' => 'No valid ticket-stub pair found' ,
	'err_timeout' => 'Time out' ,
	'err_areaorref' => 'Invalid area or referer' ,
	'fmt_prompt4repost' => 'error(s) found:<br /><span style="background-color:red;font-weight:bold;color:white;">%s</span><br />Confirm it.<br />And do you want to post again?' ,
	'btn_repost' => 'repost' ,
) ;


?>